# This is a basic workflow to help you get started with Actions

name: Black Code Formatter

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Black Code Formatter
    runs-on: ubuntu-latest
    steps:
      - name: Black Check
        uses: jpetrucciani/black-check@19.10b0
        with:
          # File or directory to run black on
          path: "src/"
